### ISSUE TITLE
QC check for curation mistakes

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/ABA_Uberon#32]
Just realised I made a mistake in curation and want to avoid this in the future.
2 QC checks that I would like implemented. 

1) No MBA term should be mapped to more than once - I think the easiest way is to check on the robot template that no term in ID column that appears more than once is mapped different. Alternatively no duplicates on ID column and we clean up the template (there are full duplicates atm) 

2) ID column and Label should match up when compared to the MBA heirachy graph thing that we get from Allen side.

No rush at all @hkir-dev but could you help me look into these QC please? thanks :)

**Comment by hkir-dev** [comment]
QC check implemented and merged
